[default]
EXTENSIONS = [
    'app.ext.database:init_app',
    'app.ext.serializer:init_app',
    'app.ext.commands:init_app',
    'app.controllers:init_app'
]

[development]
# SQLALCHEMY_DATABASE_URI = 'sqlite:///development.db'
SQLALCHEMY_DATABASE_URI = 'postgresql://postgres:postgres@localhost:5432/aluraflix'

[testing]
TESTING = true
SQLALCHEMY_DATABASE_URI = 'sqlite:///'